# Default config for PPE model quantization
source_pt_model_path: "model output/best.pt"
openvino_export_dir: "model_quantization/artifacts/openvino_fp32/"
int8_output_dir: "model_quantization/artifacts/openvino_int8/"
calibration_images_dir: "model_quantization/artifacts/calibration_images"
calibration_sample_size: 200
imgsz: 640
class_names:
  0: helmet
  1: person
  2: safety_vest
device: "CPU"
